### ISSUE TITLE
amigaos4 build

### ISSUE THREAD

**Issue by kas1e** [ptitSeb/hydracastlelabyrinth#3] opened 2018-12-30 19:48 UTC
I was able to build binary for aos4, but then it crashes from start, i check the code and it has some getenv("HOME") things in the files:

main.c:

`	#ifdef __amigaos4__`
`		strcpy(buff,"PROGDIR:.hydracastlelabyrinth");`
`	#else`
`		strcpy(buff, getenv("HOME"));`
`		strcat(buff, "/.hydracastlelabyrinth");`
`	#endif`

ini.c in 3 places:

`		#ifdef __amigaos4__`
`		strcpy(fullPath, "PROGDIR:.hydracastlelabyrinth/");`
`		#else`
`		strcpy(fullPath, getenv("HOME"));`
`		strcat(fullPath, "/.hydracastlelabyrinth/");`
`		#endif`

and game.c in one place:

`void game()`
`{`
`#ifdef _SDL`
`	#ifdef __amigaos4__`
`	const char* home = "PROGDIR:";`
`	#else`
`	const char* home = getenv("HOME");`
`	#endif`
`	if(home) `
`	{`
`		#ifdef __amigaos4__`
`		strcpy(savename, home);`
`		strcat(savename, ".hydracastlelabyrinth/");`
`		#else`
`		strcpy(savename, home);`
`		strcat(savename, "/.hydracastlelabyrinth/");`
`		#endif`
`		strcpy(savemap, savename);`
`		strcat(savename, "save.tmp");`
`		strcat(savemap, "save.map");`
`	} else {`
`		strcpy(savename, "data/save.tmp");`
`		strcpy(savemap, savemap);`
`	}`
`#endif`

After that it  create 640x480 window, write in console : 

`Hydra Castle Labyrynth, Windowed 640x480 scale=x2, using Joystik=1` 

Then it create for me .hydracastlelabyrinh directory in which "system.ini" file, and the it crashes on the PHL_LoadBMP() , which i assume again, because of different endianes :(

**Comment by ptitSeb** [comment] 2018-12-30 20:00
Ah yes, maybe it needs some bigendian fixes. I'll check that.

**Comment by ptitSeb** [comment] 2018-12-30 20:28
Ok, I have pushed some commit. Maybe it start now.

**Comment by kas1e** [comment] 2018-12-30 20:36
Tried , nope, it crashes same on PHL_LoadBMP().. :(

When it build it produce some warning about :

`amigaos.h:15:28: note: expected ‘uint32_t *’ {aka ‘unsigned int *’} but argument is of type ‘long unsigned int *’`

and `qda.c:53:12: warning: passing argument 1 of ‘BE32’ from incompatible pointer type` , but they probabaly harmless ?

**Comment by ptitSeb** [comment] 2018-12-30 21:00
Mmm, I would expect `long unsigned int` and `uint32_t` to be the same. Strange. (can you check if sizeof(long unsigned int)==4?)

Can you try to put some debug printf, because I haven't seen much bigendian trap in the code (the palette stuff maybe is wrong, but that shouldn't crash, just looks weird).

**Comment by kas1e** [comment] 2018-12-31 08:55
Added debug to see where it crashes exactly, and this is sdl2/graphics.c , line 203, which are:

`int tmp = fread(QDAFile, 1, headers[index].size, f);`

Our fread :)

**Comment by kas1e** [comment] 2018-12-31 08:56
And i can see, that before crash, it eat up about 800mb (!) of main memory, which mean something read/write in some very wrong way

**Comment by ptitSeb** [comment] 2018-12-31 09:02
Can you `printf("%d", sizeof(long unsigned int));` also ?

**Comment by kas1e** [comment] 2018-12-31 09:05
Yeah, it is 4

**Comment by ptitSeb** [comment] 2018-12-31 11:58
Strange.
Just below the last `BE32(...)` in line 55 of `qda.c` can you add
```
printf("headers[%d]: offs=%p, sz=%d, bytes=%d\n", headers[i].offset, headers[i].size, headers[i].bytes);
```
To see what's going on...

**Comment by kas1e** [comment] 2018-12-31 12:23
There is:
http://kas1e.mikendezign.com/aos4/gl4es/games/hcl/hcl.txt

**Comment by ptitSeb** [comment] 2018-12-31 13:51
Mmm, no I forget something. Here is the correct line:
```
printf("headers[%d]: offs=%p, sz=%d, bytes=%d\n", i, headers[i].offset, headers[i].size, headers[i].bytes);
```

**Comment by kas1e** [comment] 2018-12-31 15:17
There is:
http://kas1e.mikendezign.com/aos4/gl4es/games/hcl/hcl2.txt

**Comment by ptitSeb** [comment] 2018-12-31 15:56
And there is the `BE32(...)` stuff before???

**Comment by ptitSeb** [comment] 2018-12-31 16:01
Ok, found the issue, and just pushed a not commit

**Comment by kas1e** [comment] 2018-12-31 18:24
Oh yes ! It runs, works, plays, i can heard sounds, but no music strangely .. is music works for you ?

**Comment by kas1e** [comment] 2018-12-31 18:38
Anyway,  music can wait for later, as whole game works, so i probabaly can give it to testers with joystick, to see how it works ?

**Comment by ptitSeb** [comment] 2018-12-31 18:55
Music are midi tracks, so needs timidity on Linux to works. No ideas how midi music are played back on AmigaOS. (on some other platforms, midi are replaced with mp3 or something else because they can be tricky to use).

Yeah, testing joystick code will help (hopefully, that code just works).

**Comment by kas1e** [comment] 2018-12-31 22:37
I know we do have timidy, probably i just need to install it , so music will just start to works. Will check it tomorrow.. Anyway, i send test archive to 2 testers, let's see how it will be. Hope it all will just works :)

**Comment by kas1e** [comment] 2019-01-01 09:21
Got answer from one tester:

>I tested the game with Competition Pro USB. The game character moves left, right, up and down with the joystick. But pressing fire buttons 1 and 2 nothing happens. Pressing buttons 3 and 4 the character moves left and right. The joystick was recognized automatically.

Is it mean our sdl2 need some more love or it expected to be like this ?

**Comment by ptitSeb** [comment] 2019-01-01 10:00
I was expecting buttons to work. The Gamecontroller interface of SDL2 is very simple to use, and you don't need to setup any mapping in the program: when a controller is recognise, you simple have pad and buttons and everyhting already configured (well, of course there is the possibility to add a mapping at runtime). So I guess there is a small issue on Amiga side, with a not entirely recognise controler for example.
I haven't tested much my implementation on linux, I'll try to do so soon. In the mean time, here is a page with some tuto on SDL Gamecontroller interface: http://lazyfoo.net/tutorials/SDL/19_gamepads_and_joysticks/index.php

**Comment by kas1e** [comment] 2019-01-01 10:25
Aha ok, so its our sdl2  then. How in that game joystik buttons react on pandora ? Jumping ? Other buttons do nothing ?

**Comment by ptitSeb** [comment] 2019-01-01 10:51
I don't need any joystick on the Pandora, there are some builtin game controller (that are wired to keys). Look at my Profile picture, it's a pandora.
Or a bigger picture:
![pandora_gorynlich](https://user-images.githubusercontent.com/3250792/50572235-7d13b600-0dbb-11e9-87d1-2b8a33b69123.JPG)

**Comment by kas1e** [comment] 2019-01-01 11:03
:) looks nice !

What i mean, is maybe in that game it exactly works like this : just up/down/left/right, and first 2 buttons do nothing , and 3,4st button also left/right just because nothing else is set on ?

**Comment by ptitSeb** [comment] 2019-01-01 11:25
I have yet to try, but no buttons are supposed to something. In fact 3 of the 4 face buttons should do things, and also 2 triggers (shoulders buttons) and Start and select also do stuffs.
Remember that Gamecontroller interface matchs somehow Xinput on windows, so targeting controller like the XBox360, with Pad, 2 Analogs, 4 faces buttons, 4 triggers and a start and back buttons...

**Comment by kas1e** [comment] 2019-01-01 15:29
Got an answer from our SDL2 developer, and that what he say:

>It supports only one joystick currently, Competition Pro. Some pads like XBOX-360 and Steam controller were not recognized by AmigaInput so they cannot be used right now. Reference: 
https://github.com/AmigaPorts/SDL/blob/master/src/joystick/SDL_gamecontrollerdb.h#L590

This database can be appended by using test/controllermap which generates entries. I have made a test archive available ( http://capehill.kapsi.fi/sdl2/SDL_joystick_test.lha ) that can be used to:

1) test (AI-compatible) joystick: testjoystick
2) test gamecontroller (Competition Pro only!): testgamecontroller
3) configure mappings: controllermap. If you have some joystick you can send the mappings to me or make a PR on Github.

I just tested Competition Pro using test/testgamecontroller application. Directions worked, same with four buttons: A, B, X and Y.

But for tester something still wrong with HCL .. go figure ..

**Comment by ptitSeb** [comment] 2019-01-01 16:32
So, I finaly tested on my side... and yes, it doesn't work :( I have the same behaviour as your tester.

I'll fix that.

**Comment by ptitSeb** [comment] 2019-01-01 17:06
Ok, I think I have fixed it now. Check with latest commit (by the way, it's a pretty nice game).

**Comment by kas1e** [comment] 2019-01-01 21:31
Cool ! Sended it to tester, wait for his answer, but probabaly all will be fine then.
Also will try to deal with timidy on my setup, and then can release aos4 version of HCL as well :)

**Comment by kas1e** [comment] 2019-01-02 06:32
Have answer about new build: 

>Now fire buttons 1 and 2 are jump and attack but I can't move the character any more with the new build.

**Comment by ptitSeb** [comment] 2019-01-02 06:41
Really? Strange. How that controller looks like? The character movement, is this done using analog stick or dpad?

**Comment by kas1e** [comment] 2019-01-02 16:14
Waiting answer from tester, but strange that before only up/down/left/right works, and no fire/jump buttons, but with last gix buttons start works, but no left/right/up/down. 

On linux all fine ?

**Comment by ptitSeb** [comment] 2019-01-02 16:28
I couldn't test completly on linux yesterday.

The direction was working before it was the "Joystick" interface that was working, not the Gamecontroler that was not enabled. So enabled Gamecontroler interface and made sure to not use Joystick interface if the joystick is recognised as a Gamecontroleur (so the mapping is correct out-of-the-box)

**Comment by kas1e** [comment] 2019-01-02 17:57
Tester didnt answer at moment, just want to be sure that on linux all allright so issue on our side.

Or, i just need to buy Competition Pro and all can be tested easy :)

**Comment by ptitSeb** [comment] 2019-01-02 18:35
My son just tested on Linux (with an XBox360), and it worked perfectly.

**Comment by kas1e** [comment] 2019-01-03 08:42
Did i understand right, that there is 2 ways to handle joysticks in SDL2 apps ? One are SDL joystick API and another one is SDL game controller API  ?

**Comment by kas1e** [comment] 2019-01-03 09:31
Btw, found probabaly another endian issue : when i play in game, then exit, then start it again , i have words "ops, blalbal you need to load blblalb" , so i choice "load game", and it crashes then in the game.c:945, hcl:LoadScreen()

**Comment by ptitSeb** [comment] 2019-01-03 09:36
Yes.
The Joystick API is the legacy API. It was already present in SDL 1.2, and basically, every joystick works with this API. The issue with this API is that every Axis (i.e. analog parts) and every buttons (and also, Hats, that most of the time are DPad) are just Numbers. You don't know which number is which physical button on the jostick, unless you use the Joystick name (the API can provide that) with some mapping...
The Gamecontroller API just does that. It has a database of joystick and provide a unified API. You just ask for Button 'A' or X axis from left Thumb...

**Comment by ptitSeb** [comment] 2019-01-03 09:36
> Btw, found probabaly another endian issue : when i play in game, then exit, then start it again , i have words "ops, blalbal you need to load blblalb" , so i choice "load game", and it crashes then in the game.c:945, hcl:LoadScreen()

Yes, probably, I'll look into that latter.

**Comment by ptitSeb** [comment] 2019-01-03 11:06
Can you try with latest commit, hopefully the crash at reload is fixed.

**Comment by kas1e** [comment] 2019-01-03 12:05
Sec, will check.
But just in case ,  for us PROGDIR:data/ and just "data/" , mean the same - directory from which we run binary.

I also tryied to run 3 times old binary and doing "load game", and for second load game it didn't crash, just saying map not found, and for 3st run, it loads new game.. Strange..

Is there any button so i can do "save game", to see if it works for save/load ?

ps. i also install "timidity" , and music works !

**Comment by ptitSeb** [comment] 2019-01-03 13:00
Yeah I just added "PROGDIR:" just in case.
I don't see any potential crash, but I guess there is still some bigendian issue. I need to think about it more.

And no, there is no "Save". It's automatic, and design to forbid abuse of the save system. The save state is created when you quit, and is delete when you load it...

**Comment by ptitSeb** [comment] 2019-01-03 14:00
Ok, I have pushed something for the Load/Save issue, if you can try.

**Comment by kas1e** [comment] 2019-01-03 20:25
As for competition pro and whole joystick's thing..

Testers send me a link on, it is digital stick + 4 buttons:
https://www.speedlink.com/en/COMPETITION-PRO-USB-SPORTS-TOURNAMENT-EDITION-EU-VERSION-BLACK-RED.html

Also i bring on SDL2's os4 mantainer all the question about, and that what he answer:

> I checked some code, HCL makes an assumption that there are leftx/lefty axes defined: https://github.com/ptitSeb/hydracastlelabyrinth/blob/master/src/sdl2/input.c#L201
Competition Pro has mapping for only rightx/righty: https://github.com/AmigaPorts/SDL/blob/master/src/joystick/SDL_gamecontrollerdb.h#L590
Regarding joystick API, I don't know right now what are the button numbers for Competition Pro. Probably from 0 to upwards, I have used "0" in Super Methane Bros and some other apps. Then again, if we check Hydra code, buttons 0-3 set directions: https://github.com/ptitSeb/hydracastlelabyrinth/blob/master/src/sdl2/input.c#L156
What exactly should happen when joystick fire buttons (Comp Pro has 4) are active?

ps. will check soon that load/save stuff

**Comment by ptitSeb** [comment] 2019-01-03 20:45
So, ok, only Right axis and no Left axis explain why there is no direction with Competition Pro. I'll do a `#ifdef` to add right axis on amiga. The choice to use Right axis and Left is a bit strange, I would assume default to be left, but it doesn't matter much, I'll adapt the code.

For the buttons, that mapping is when using the Joystick interface, not the Gamecontroller one. Anyway, that mapping is bad, and I'll just put some default value, not that xbox360 mapping (that will be used in Gamecontroller mode anyway).

**Comment by kas1e** [comment] 2019-01-03 20:47
I mostly about if we need to fix something in SDL2 to make it all be easy to use later when crosscompile anything else (so we will have no needs for ifdef amiga)..

**Comment by kas1e** [comment] 2019-01-03 20:49
Btw, for making "save" working, all i need its start game, pass one screen, then press "esc", choice exit, and by logic it should do "save" ?

**Comment by kas1e** [comment] 2019-01-03 20:55
And i think i found some bug : if you run HCL in window mode, and then press "Close gadget" on the window, then, instead of quit, its instead start a new game. Like, it send wrong break, or not full interrupt main game's code.

**Comment by ptitSeb** [comment] 2019-01-04 10:00
So I have pushed some commits.
I fixed the "Quit" by GUI issue.
I forced the use of Right Stick for Gamecontroller on Amiga, and used simpler button and axis mapping on Joystick mode.
Now, for Gamecontroller, the idea behind this API is to propose a Plug'n Play way to use a joystick: you plug it in, and because the Layout and mapping is standardized (look at XB360, XBOne, PS3 or PS4 controlleurs: they all offerts similar basic functions on a similar layout: left and right stick, left dpad, 4 fae buttons, 4 triggers, 1 back and 1 start buttons basically). So, for Gamecontroller, the point is to not have any config screen, it just work, with a fixed layout.

For joystick, a config screen would be needed. But as I don't like programming GUI, I don't think I'll do that (plus, it's a long and tedious work to program that GUI for joystick option for just 20 sec of use). I will, maybe, think about some config field in the config file...

**Comment by kas1e** [comment] 2019-01-04 15:54
Did i understand right, that in Hydra you have support at the same time 2 apis ? Joystick one and Gamecontroller one ? And if so, which one are in favor ? I mean, you says that for buttons some mapping was used in Joystick mode, so i just looses there :)

Also, about axis, didn't SDL offers a way to query axis and in case of failure, return NULL ? If so, it can be better to not have any ifdefs, but just do query all those 6 or how many axis SDL provide, and those which is not NULL are our ones.

As for Joystick interface in whole : for sure it have no needs to be supported. Programming gui (always new) for every new port its just boring and not interesting work for sure. Its enough to just deal with Gamecontroller, write one time good code which works everywhere, and then just copy+paste it all the time . Programming gui its really time consuming and not worth of it

**Comment by ptitSeb** [comment] 2019-01-04 16:05
For Hydra I do that: I query SDL if there is at least 1 joystick connected. If yes, I try to use Gamecontroller API first. If the joystick is recognized as a Gamecontroller by SDL, I use that API. If not, I fallback to Joystick mode.

About Axis, yes, you can query SDL the number of Axis, Buttons and Hat per joystick. I don't do that because I have no configuration screen, so that information is useless, plus I simply used the the X & Y of the Axis 0, nothing fancy here (well, for the Joystick interface, because for the Gamecontroller interface I took the left stick because it's the one you normally use for Movement, the Right Stick is for Camera usualy).

**Comment by ptitSeb** [comment] 2019-01-04 16:07
Also, Hydra have both Jostick and Gamecontroller because I wrote the SDL2 backend after I wrote the SDL1 backend. SDL1 only have Joystick API, so reused most of the code and then add Gamecontroler API.
But for frikining-shark, I target to use only the Gamecontroller API...

**Comment by kas1e** [comment] 2019-01-04 16:15
Tested latest version, and yeah, QUIT from gui works fine now. Through found another bug. To reproduce you need to do that:

run hydra
press new game
once game starts, press "esc"
choice there "options"
there choice XCBT from ON to OFF, or from OFF to ON , doesn't really matter
then press BACK
then press EXIT
..crash..

Crash point out to `main()->game()->SDL_Free()`

ps. Yeah just GameController API is enough for sure.

**Comment by kas1e** [comment] 2019-01-04 16:17
Ha, its probabaly enough to just do switch from ON to OFF, and then again from OFF to ON, to have that crash, no needs for exit

**Comment by kas1e** [comment] 2019-01-04 16:18
If it reproducable for you at least .. (it can be some fresh SDL2 bug on our side for example .. hope that not)

**Comment by ptitSeb** [comment] 2019-01-04 16:19
I don't reproduce the issue. Can you have a more detailled backtrace?

**Comment by kas1e** [comment] 2019-01-04 16:19
Give me a second, i will try with some old-public version of SDL2 firstly.

**Comment by ptitSeb** [comment] 2019-01-04 16:20
(XCBT is fact XBRZ right, the upsampling algorithm?)

**Comment by kas1e** [comment] 2019-01-04 16:23
Yes, i tested with previous SDL version - bug still there. 
More of it, when i switch it , MIDI music stop working as well (but probabaly that intendent). I will made detailed stacktrace with -gstabs now, one moment

**Comment by kas1e** [comment] 2019-01-04 16:28
There is:
http://kas1e.mikendezign.com/aos4/gl4es/games/hcl/Crashlog_hcl_2019-01-02_19-31-26.txt

Check stack trace part plz

**Comment by kas1e** [comment] 2019-01-04 16:29
Probabaly when i first time swith the value, and timidy stops, that mean memory trashing already happens, and then, when i swtch it second time, it crashes for real

**Comment by ptitSeb** [comment] 2019-01-04 16:32
Ah, it's a problem with the Music beeing free.

I see what's wrong, I'll fix that.

**Comment by ptitSeb** [comment] 2019-01-04 16:42
Ok, it should be fixed now.

**Comment by kas1e** [comment] 2019-01-04 16:50
Yeah, it is ! Cool :)

So, now to understand how that "save/load" thing works. For me, at moment, when i press "new game" play a bit, then exit (doesn't matter if via quit gadget in gui, or via options/exit), and then start a game, "load game" just start a new game. It is intendent ? Or it should load the place where i stop playing ?

**Comment by ptitSeb** [comment] 2019-01-04 17:03
There are save point, you need to go there to have some save state that is not at the beggining of the level.

At the start of the game, go left, and up if you can, that should help start the game (you need to find a treasure chest, inside is a pick axe that can destroy red block, that will help you get the key to the 1st boss, and there is a save point before entering this dungeon).

**Comment by kas1e** [comment] 2019-01-04 17:08
Aha, will try now.

What is interseting also, is that seeing videos, i see how they can broken those red stones, but is it ok that by default i can't and i need to take some weapon for firstly ?

Edit: ops.. you already answer about red stones :)

**Comment by kas1e** [comment] 2019-01-04 17:17
Strange things that those warnings about "save point" i was have when just play in first screens (i for sure didn't touch save points). Maybe it was some side effect of bug with that free_music thing ? 

Ok will play a bit more now to see if save states works.

It also wasn't easy to found key which open the treasure chest, its somewhere on my numpad in end :)

**Comment by ptitSeb** [comment] 2019-01-04 17:48
Well, found a save point and you'll know for sure if it's works.
Also, I haven't checked the bigendian stuff for saves. That means they sould work on the amiga, but they will not be shareable with PC ones.

If the default keymap is not good for amiga (because there are a few keys yes), we can `#ifdef` some...

**Comment by kas1e** [comment] 2019-01-04 19:04
Yeah, probabaly need a bit of redefine for keys ..

At least on my keyboard, numpad's left and right, seems works wrong : you press it one time, and it like "pressed always", and that can be ok, but then, when i need to stop that behaviour, i can't easyly stop it, i need to press many times left/right. 

Also for me, taking the treasure cheast was number "8", and only on numpad. Is it also intendent ? And also "space" are the same as "esc", while usually space its something like action (or just pause in end of all).

For amigaos it can be something like this:

esc: as it (for menu)
enter: as it (for select items)
left/right/up/down: as it

space: jump
left ctrl: hit by sword
other ones are : q,w,e,r and how many of them in a row.

Through strange about that "8" on numpad, from where it come ..

**Comment by kas1e** [comment] 2019-01-04 19:08
Btw, i started to port Eldritch , all progress well, but seems there some issues in terms of 8.2.0 gcc, so if you doesn't mind to create ability to create tickets in Eldritch repo, i will be glad to start another amigaos4 build thread :)

**Comment by ptitSeb** [comment] 2019-01-04 19:35
I'll check for the keymap for HCL.

For Eldritch, it's been a long time since I build it. I have just enable the issues for this project. Also, I'll need to test, check this is still working. Also, note that this one is a GLES2 port, no need for GL4ES there (that's the project I've done that was the "POC" of gl4es on GLES2 was something possible in fact).

**Comment by kas1e** [comment] 2019-01-04 20:15
Found savepoint, load game works :)

Strange thorugh why before i have those strange issues .. Probabaly was related to the memory trashing caused by that "free music" stuff.

I also sended new version to testers to check how it now with joysticks.

**Comment by kas1e** [comment] 2019-01-04 22:26
Have answer from one tester with "Thrustmaster dual analog 3.2" joystick (or pad, dunno), he say all fine now.

But then i assume it is fallback to the old joystick api, as in our sdl2 gamecontrollers database we have one single entry for "competition pro" one.

Question is: if sdl2 have in gamecontrollers api just one entry for "competition pro" joystick, will other ones completely not works, or works "somehow" ? I assume if no entry in database then totaly not works, right ?

**Comment by ptitSeb** [comment] 2019-01-04 23:11
If the joystick is not in the database, it will not be useable as a "gamecontroller". It seems there is an API with easy GUI to set the mapping (I think I read that on some SDL2 doc), but I haven't looked into this at all, so I don't know how difficult it is to had gamecontroller mapping stuff.

**Comment by kas1e** [comment] 2019-01-05 07:27
So if joystick not in database, and no fallback to old api, it will just not work ?

**Comment by ptitSeb** [comment] 2019-01-05 09:41
Yep

**Comment by kas1e** [comment] 2019-01-05 11:40
After playing a bit more in it, i think we can keep the keys mapping as it.. Not big deal, i just will note in the readme how to use it and that all..

I made also a video , check this out:
https://www.youtube.com/watch?v=vc7WpxpycTg

So far all looks fine, and i can put release archive on our depo.

That was some "friking shark joystik test" leading to another game, thanks a bunch !

**Comment by kas1e** [comment] 2019-01-05 11:51
Btw, in the input.c i can see also keys d,r,w,e are used , but so far i only got to use:

left/right/up/down - character control
 x - jump
 s - attack
 up - to take things (like treasure cheats, keys, etc)
 enter - inventory
 esc/space - to the menu

But what to do those ones:

 d - ? writen as bFaceRight
 r - ? writen as bR
 w - ? writen as bL
 e - ? writen as bFaceUp

(just want to put it all clear to the readme)

**Comment by ptitSeb** [comment] 2019-01-05 11:54
Nice video (there is a typo in "Labyrinth" in the youtube video)

The key "bR" and "bL" and "bFaceRight" are for the secondary weapon. You can have many (you have 0 at first), and bR and bL allow fast switch between them (previous/next weapon type), without going to the inventory screen.The bFaceRight is used to use that weapon. Last Face button is not used.

**Comment by kas1e** [comment] 2019-01-05 11:58
Yeah, fixed vid, thanks for explain, will made a release now.

**Closed as completed** 2019-01-05 19:59 UTC
